name: devbox

services:

  devbox:

    image: devbox-lite

    container_name: devbox-lite

    hostname: devbox-lite

    working_dir: /workspace

    stdin_open: true

    tty: true

    restart: unless-stopped

    ports:
      - "6080:6080"
      - "6081:6081"

    volumes:
      - ../../:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
      - devbox-postman-data:/root/.config/Postman
      - devbox-bruno-data:/root/.bruno

    environment:
      TZ: Asia/Tehran

    networks:
      - devbox-network

volumes:
  devbox-postman-data:
  devbox-bruno-data:

networks:
  devbox-network:
    name: devbox-network
    driver: bridge
